name: Post API tests

on: [push. pull_request]

jobs:
	test:
	runs-on: ubuntu-latest

	steps:
	- uses: actions/checkout@v2
	- name: Install Newman
	run: npm install -g newman
	- name: Run Postman Collection
	newman run .\Postman\Collections\Exercise1.postman_collection.json -e .\Postman\Environments\mock_Api_url.postman_environment.json\
	git add .
	git commit -m "Added Postman Workflows"
	git push origin master
